name = "PkgGraph"
uuid = "f9c1b9e4-72e8-4a14-ade5-14f45fc35f11"
authors = ["Tomas Fiers <tomas.fiers@gmail.com> and contributors"]
version = "0.3.0-dev"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
DefaultApplication = "1"
URIs = "1"
julia = "1.6"
