name = "PkgGraphs"
uuid = "e1fb1e7a-e19f-4e1c-a7f1-cf21066b67cc"
authors = ["Tomas Fiers <tomas.fiers@gmail.com> and contributors"]
version = "0.2.0"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
DefaultApplication = "1"
URIs = "1"
julia = "1.6"
