name: Docs

# Build docs when anything changes except the tests.
on:
  push:
    branches: ['main']
    paths-ignore:
      - test/**
    tags: ['*']
  pull_request:

concurrency:  # See Tests.yml for explanation.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
        with:
          cache-compiled: true
          # See https://github.com/julia-actions/cache#inputs and the linked #11
      - run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
        # ↪ This is necessary because we use an unreleased version of Documenter.
        #    Thread I started about this: https://discourse.julialang.org/t/91498/
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
