
# Provides a 'Run Workflow' button [at https://github.com/tfiers/PkgGraph.jl/actions/workflows/Register.yml]
# that makes a commit with an updated version in Project.toml, and then comments on that
# commit with `@JuliaRegistrator register`, to create a PR in the General registry.

name: Register Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to register (provide all three components) or component to bump (major|minor|patch):'
        required: true
jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
